# 셔클 효과 분석 설정 파일 예시
# 이 파일을 복사하여 원하는 설정으로 수정하세요.

# 데이터 설정
data:
  path: '../data/shucle_analysis_dataset_20250929.csv'
  encoding: 'utf-8'
  zone_types:
    - '도시'
    - '농어촌'
  time_columns:
    도보시간:
      - public_total_walking_time_seconds
      - drt_total_walking_time_seconds
    탑승시간:
      - public_onboard_time_seconds
      - drt_onboard_time_seconds
    대기시간:
      - public_waiting_time_seconds
      - drt_waiting_time_seconds
    총 이동시간:
      - public_total_time_seconds
      - drt_total_trip_time_seconds

# 시각화 설정
visualization:
  # 생성할 시각화 타입들
  types:
    - boxplot
    - violin
    - boxen

  # 모든 시각화에 공통 적용되는 설정
  common_settings:
    title_prefix: '셔클 도입 효과 분석'
    ylabel: '시간(분)'
    figsize: [15, 8]
    show_outliers: false
    show_mean: false
    show_mean_value: true
    mean_format: '{:.1f}분'
    mean_margin: 1.0
    clip_percentile: 0.99

    # 평균값 위치 전략 (사용자가 직접 제어 가능)
    mean_position_strategy: 'fixed_percentage'  # 'adaptive', 'fixed_top', 'fixed_percentage'
    fixed_y_percentage: 0.85  # fixed_percentage일 때 사용할 비율 (0.0-1.0)

    # Y축 범위 직접 지정 (null이면 자동)
    y_axis_min: null  # 예: 0
    y_axis_max: null  # 예: 100

    # 평균값 텍스트 색상 사용자 지정
    mean_text_colors:
      대중교통: 'red'
      셔클: '#1F4EAA'

  # 박스플롯 전용 설정
  boxplot:
    # 박스플롯에만 적용할 특별한 설정이 있다면 여기에

  # 바이올린 플롯 전용 설정
  violin:
    show_box: false  # 내부 박스 표시 여부
    mean_position_strategy: 'fixed_percentage'
    fixed_y_percentage: 0.75  # 바이올린 플롯에서는 좀 더 낮은 위치
    clip_percentile: 0.98  # 바이올린 플롯에서는 더 많이 자르기

  # Boxen 플롯 전용 설정
  boxen:
    mean_position_strategy: 'fixed_top'
    clip_percentile: 0.95

# 통계 분석 설정
statistics:
  percentiles: [0.25, 0.5, 0.75, 0.9]

# 출력 설정
output:
  save_plots: true       # 플롯을 파일로 저장할지 여부
  show_plots: true       # 플롯을 화면에 표시할지 여부
  save_statistics: true  # 통계 결과를 파일로 저장할지 여부
  directory: '../output' # 출력 디렉토리
  format: 'png'         # 플롯 파일 형식 ('png', 'pdf', 'svg')
  dpi: 300              # 해상도

---

# 추가 설정 예시들:

# 예시 1: Y축 범위를 직접 지정하고 싶은 경우
# visualization:
#   common_settings:
#     y_axis_min: 0
#     y_axis_max: 120
#     mean_position_strategy: 'fixed_percentage'
#     fixed_y_percentage: 0.9  # Y축 최대값의 90% 위치에 평균값 표시

# 예시 2: 다른 색상 조합을 사용하고 싶은 경우
# visualization:
#   common_settings:
#     mean_text_colors:
#       대중교통: '#FF6B6B'  # 밝은 빨강
#       셔클: '#4ECDC4'     # 청록색

# 예시 3: 적응형 위치와 고정 위치를 조합하고 싶은 경우
# visualization:
#   common_settings:
#     mean_position_strategy: 'adaptive'  # 기본은 적응형
#   boxplot:
#     mean_position_strategy: 'fixed_top'  # 박스플롯만 상단 고정
#   violin:
#     mean_position_strategy: 'fixed_percentage'
#     fixed_y_percentage: 0.8

# 예시 4: 특정 시각화만 생성하고 싶은 경우
# visualization:
#   types:
#     - boxplot  # 박스플롯만 생성

# 예시 5: 고해상도 PDF로 저장하고 싶은 경우
# output:
#   format: 'pdf'
#   dpi: 600
#   show_plots: false  # 파일 저장만 하고 화면 표시는 안함